// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFVvMaHKM_P_M4_Y3MaevCWWS_m07v9Y0',
    appId: '1:1070325915813:web:45d66ca5d4741c5fac2d4c',
    messagingSenderId: '1070325915813',
    projectId: 'trilhas-phb',
    authDomain: 'trilhas-phb.firebaseapp.com',
    storageBucket: 'trilhas-phb.appspot.com',
    measurementId: 'G-H9K86GQTHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkCor62va5PwGjG1nygdCXhnUgCAx8vWE',
    appId: '1:1070325915813:android:c5d2b9c2f3a71baaac2d4c',
    messagingSenderId: '1070325915813',
    projectId: 'trilhas-phb',
    storageBucket: 'trilhas-phb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPam91H-blQeGStE39iTA30qcyU01eFaQ',
    appId: '1:1070325915813:ios:a6e1e89d33918596ac2d4c',
    messagingSenderId: '1070325915813',
    projectId: 'trilhas-phb',
    storageBucket: 'trilhas-phb.appspot.com',
    iosBundleId: 'com.example.trilhasPhb',
  );

}